/** Homepage / comparison showcase entries for non-loan marketplaces */
export const MARKETPLACE_SHOWCASE_PRODUCTS = [
  {
    slug: 'insurance',
    apiKey: 'insurance',
    kind: 'marketplace',
    route: '/insurance-marketplace',
    label: 'Insurance',
    shortLabel: 'Insurance',
    icon: 'Shield',
    description: 'Compare life, health, motor, and travel insurance from trusted insurers.',
    interestRange: 'From ₹500/month',
    features: ['Life & health plans', 'Motor insurance', 'Tax benefits (80C/80D)', 'Quick policy quotes'],
    color: '#059669',
    visibilityKey: 'insuranceMarketplace',
  },
  {
    slug: 'mutual_fund',
    apiKey: 'mutual_funds',
    kind: 'marketplace',
    route: '/mutual-fund-marketplace',
    label: 'Mutual Fund',
    shortLabel: 'Mutual Fund',
    icon: 'TrendingUp',
    description: 'Discover SIP and lump-sum mutual fund options matched to your goals.',
    interestRange: 'SIP from ₹500/month',
    features: ['Equity & debt funds', 'SIP from ₹500', 'Goal-based investing', 'Top-rated AMCs'],
    color: '#d97706',
    visibilityKey: 'mutualFundMarketplace',
  },
  {
    slug: 'fixed_income',
    apiKey: 'fixed_income',
    kind: 'marketplace',
    route: '/fixed-income-marketplace',
    label: 'Fixed Income',
    shortLabel: 'Fixed Income',
    icon: 'Landmark',
    description: 'Compare fixed deposits across banks, corporate FDs and NBFC FDs.',
    interestRange: 'Stable returns',
    features: ['FD rate comparison', 'Lock-in & withdrawal rules', 'Monthly/quarterly payouts', 'Quick apply links'],
    color: '#0f766e',
    visibilityKey: 'fixedIncomeMarketplace',
  },
  {
    slug: 'post_office',
    apiKey: 'post_office',
    kind: 'marketplace',
    route: '/post-office-marketplace',
    label: 'Post Office',
    shortLabel: 'Post Office',
    icon: 'Mailbox',
    description: 'Compare PPF, NSC, KVP, SCSS, MIS and other India Post savings schemes.',
    interestRange: 'Govt-backed returns',
    features: ['PPF & NSC', 'SCSS & MIS', 'Maturity calculator', 'Tax benefit overview'],
    color: '#b45309',
    visibilityKey: 'postOfficeMarketplace',
  },
  {
    slug: 'government_scheme',
    apiKey: 'government_schemes',
    kind: 'marketplace',
    route: '/government-schemes-marketplace',
    label: 'Government Schemes',
    shortLabel: 'Govt Schemes',
    icon: 'Landmark',
    description: 'Explore loans, subsidies, pensions, and social security programs.',
    interestRange: 'Subsidies & loans',
    features: ['PM Mudra & PMEGP', 'Pension schemes', 'Subsidy programs', 'Eligibility compare'],
    color: '#1d4ed8',
    visibilityKey: 'governmentSchemesMarketplace',
  },
  {
    slug: 'investment',
    apiKey: 'investment_products',
    kind: 'marketplace',
    route: '/investment-marketplace',
    label: 'Investment',
    shortLabel: 'Investment',
    icon: 'Gem',
    description: 'Compare sovereign gold bonds, ETFs, bonds, REITs, and InvITs.',
    interestRange: 'Diversified assets',
    features: ['SGB & gold ETFs', 'Bonds & G-Secs', 'REIT & InvIT', 'Risk & returns compare'],
    color: '#7c3aed',
    visibilityKey: 'investmentMarketplace',
  },
];

export const COMPARE_SHOWCASE_PRODUCT = {
  slug: 'compare_products',
  kind: 'compare',
  route: '/product-comparison',
  label: 'Compare Products',
  shortLabel: 'Compare',
  icon: 'GitCompare',
  description: 'Compare loans, credit cards, insurance, and mutual funds side by side.',
  interestRange: 'All categories',
  features: ['Up to 3 products', 'Bank offer comparison', 'Insurance & MF plans', 'One-click apply'],
  color: '#6366f1',
};
