/** Planning hub product cards — deep-link to existing marketplaces + calculators. */

export const RETIREMENT_PLANNING_PRODUCTS = [
  {
    id: 'pension-calc',
    title: 'Pension Calculator',
    description: 'Estimate monthly pension from your retirement corpus.',
    icon: 'Wallet',
    type: 'calculator',
    path: '/resources/calculators/pension',
  },
  {
    id: 'retirement-corpus',
    title: 'Retirement Corpus Planner',
    description: 'Plan how much you need and monthly SIP required.',
    icon: 'Target',
    type: 'calculator',
    path: '/resources/calculators/retirement-corpus',
  },
  {
    id: 'nps',
    title: 'NPS',
    description: 'National Pension System — tax benefits and long-term retirement corpus.',
    icon: 'Landmark',
    type: 'marketplace',
    path: '/government-schemes-marketplace?category=nps',
  },
  {
    id: 'annuity',
    title: 'Annuity Plans',
    description: 'Convert lump sum to guaranteed lifetime income.',
    icon: 'Shield',
    type: 'calculator',
    path: '/resources/calculators/annuity',
  },
  {
    id: 'swp',
    title: 'SWP Calculator',
    description: 'Systematic withdrawal plan for post-retirement income.',
    icon: 'TrendingDown',
    type: 'calculator',
    path: '/resources/calculators/swp',
  },
  {
    id: 'scss',
    title: 'Senior Citizen Savings',
    description: 'Government-backed scheme for senior citizens.',
    icon: 'Heart',
    type: 'marketplace',
    path: '/post-office-marketplace?category=senior_citizen_savings',
  },
  {
    id: 'pension-insurance',
    title: 'Pension & Retirement Plans',
    description: 'Insurance-backed retirement and pension products.',
    icon: 'Umbrella',
    type: 'marketplace',
    path: '/insurance-marketplace?category=retirement_plans',
  },
  {
    id: 'epf',
    title: 'EPF Calculator',
    description: 'Project your Employee Provident Fund corpus.',
    icon: 'Building2',
    type: 'calculator',
    path: '/resources/calculators/epf',
  },
];

export const TAX_SAVING_PRODUCTS = [
  {
    id: 'elss',
    title: 'ELSS',
    description: 'Equity Linked Savings Scheme — 80C with shortest lock-in.',
    icon: 'TrendingUp',
    type: 'marketplace',
    path: '/mutual-fund-marketplace?category=elss',
  },
  {
    id: 'tax-fd',
    title: 'Tax Saving FD',
    description: '5-year fixed deposit with Section 80C benefit.',
    icon: 'Landmark',
    type: 'marketplace',
    path: '/fixed-income-marketplace?category=tax_saving_fd',
  },
  {
    id: 'nps-tax',
    title: 'NPS',
    description: 'Additional ₹50,000 deduction under Section 80CCD(1B).',
    icon: 'PiggyBank',
    type: 'marketplace',
    path: '/government-schemes-marketplace?category=nps',
  },
  {
    id: 'ulip',
    title: 'ULIP',
    description: 'Unit Linked Insurance Plan with tax benefits.',
    icon: 'Shield',
    type: 'marketplace',
    path: '/insurance-marketplace?category=ulip',
  },
  {
    id: 'term-insurance',
    title: 'Term Insurance',
    description: 'Pure protection with 80D/80C benefits where applicable.',
    icon: 'HeartHandshake',
    type: 'marketplace',
    path: '/insurance-marketplace?category=term_life',
  },
  {
    id: 'hra-calc',
    title: 'HRA Calculator',
    description: 'Calculate House Rent Allowance exemption.',
    icon: 'Home',
    type: 'calculator',
    path: '/resources/calculators/hra',
  },
  {
    id: 'income-tax',
    title: 'Income Tax Calculator',
    description: 'Compare old vs new tax regime.',
    icon: 'Receipt',
    type: 'calculator',
    path: '/resources/calculators/income-tax',
  },
  {
    id: 'capital-gain',
    title: 'Capital Gain Calculator',
    description: 'LTCG/STCG tax on equity and other assets.',
    icon: 'LineChart',
    type: 'calculator',
    path: '/resources/calculators/capital-gain',
  },
  {
    id: 'section-80c',
    title: 'Section 80C Planner',
    description: 'Track ₹1.5 lakh deduction utilisation.',
    icon: 'BadgePercent',
    type: 'calculator',
    path: '/resources/calculators/section-80c',
  },
  {
    id: 'ppf',
    title: 'PPF',
    description: 'Tax-free returns with EEE status.',
    icon: 'Vault',
    type: 'marketplace',
    path: '/post-office-marketplace?category=ppf',
  },
];

export const WEALTH_MANAGEMENT_PRODUCTS = [
  {
    id: 'portfolio',
    title: 'Portfolio Analysis',
    description: 'Review your loans, investments and insurance in one place.',
    icon: 'PieChart',
    type: 'dashboard',
    path: '/customer-dashboard?tab=portfolio',
  },
  {
    id: 'goal-planning',
    title: 'Goal Planning',
    description: 'SIP calculator for any financial goal.',
    icon: 'Target',
    type: 'calculator',
    path: '/resources/calculators/goal-sip',
  },
  {
    id: 'child-education',
    title: 'Child Education Planning',
    description: 'Plan and invest for your child\'s education.',
    icon: 'GraduationCap',
    type: 'calculator',
    path: '/resources/calculators/child-education',
  },
  {
    id: 'marriage',
    title: 'Marriage Planning',
    description: 'Save systematically for wedding expenses.',
    icon: 'Heart',
    type: 'calculator',
    path: '/resources/calculators/marriage-planning',
  },
  {
    id: 'wealth-creation',
    title: 'Wealth Creation',
    description: 'Long-term SIP wealth building calculator.',
    icon: 'Gem',
    type: 'calculator',
    path: '/resources/calculators/wealth-creation',
  },
  {
    id: 'estate',
    title: 'Estate Planning',
    description: 'Guides and term insurance for legacy protection.',
    icon: 'FileText',
    type: 'content',
    path: '/legal/financial-guides',
  },
  {
    id: 'succession',
    title: 'Succession Planning',
    description: 'Nominee, will and insurance planning resources.',
    icon: 'Users',
    type: 'content',
    path: '/legal/financial-guides',
  },
  {
    id: 'mutual-funds',
    title: 'Mutual Fund Marketplace',
    description: 'Build a diversified investment portfolio.',
    icon: 'TrendingUp',
    type: 'marketplace',
    path: '/mutual-fund-marketplace',
  },
  {
    id: 'investment',
    title: 'Investment Marketplace',
    description: 'Bonds, ETFs, SGB and alternative investments.',
    icon: 'BarChart3',
    type: 'marketplace',
    path: '/investment-marketplace',
  },
  {
    id: 'fire',
    title: 'FIRE Calculator',
    description: 'Financial independence and early retirement corpus.',
    icon: 'Flame',
    type: 'calculator',
    path: '/resources/calculators/fire',
  },
];

export const PLANNING_HUBS = [
  {
    id: 'retirement',
    title: 'Retirement Planning',
    subtitle: 'Secure your golden years with the right corpus, pension and government schemes.',
    path: '/retirement-planning',
    icon: 'Sunset',
    products: RETIREMENT_PLANNING_PRODUCTS,
    gradient: 'from-amber-500 via-orange-500 to-rose-500',
  },
  {
    id: 'tax-saving',
    title: 'Tax Saving Products',
    subtitle: 'Maximise deductions with ELSS, NPS, tax FDs and smart tax calculators.',
    path: '/tax-saving',
    icon: 'Receipt',
    products: TAX_SAVING_PRODUCTS,
    gradient: 'from-emerald-500 via-teal-500 to-cyan-600',
  },
  {
    id: 'wealth',
    title: 'Wealth Management',
    subtitle: 'Goal-based planning, portfolio view and long-term wealth creation.',
    path: '/wealth-management',
    icon: 'Gem',
    products: WEALTH_MANAGEMENT_PRODUCTS,
    gradient: 'from-violet-500 via-purple-500 to-indigo-600',
  },
];
